/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melida
 */
public class AdminRezultatiTesta extends javax.swing.JPanel {

    /**
     * Creates new form AdminRezultatiTesta
     */
    public AdminRezultatiTesta() {
        initComponents();
        popuniTabelu();
    }
    
    // Popunja jTable1 sa svim ocenama za datom ucenika koje se nalaze u bazi, sortira ih po predmetu i po datumu
    private void popuniTabelu() {
      
        String upit = "SELECT *FROM Predmet INNER JOIN (Student INNER JOIN Rezultati_testa ON Student.username = Rezultati_testa.student) ON Predmet.id_predmeta = Rezultati_testa.predmet;";
        
        System.out.println(upit);
        try {
            ResultSet rezultat = DBController.require().submitQuery(upit);
            while(rezultat.next()) {
                Object[] row = { rezultat.getString("Username"), rezultat.getString("Naziv"), rezultat.getInt("Razred"), rezultat.getInt("Odeljenje"),
                    rezultat.getInt("broj_bodova"), rezultat.getBoolean("odgovor1"), rezultat.getBoolean("odgovor2"), rezultat.getBoolean("odgovor3"),
                    rezultat.getBoolean("odgovor4"), rezultat.getBoolean("odgovor5"), rezultat.getInt("redni_broj_testa")};
                ((DefaultTableModel) jTable1.getModel()).insertRow(0, row);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(OcenePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ime", "Predmet", "Razred", "Odeljenje", "broj_bodova", "zad1", "zad2", "zad3", "zad4", "zad5", "redni_broj_testa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 670, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
