/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Melida
 */
public class FrameDodajStudenta extends javax.swing.JFrame {

    /**
     * Creates new form FrameDodajStudenta
     */
    public FrameDodajStudenta() {
        initComponents();
    }
    public void DodajStudenta() throws SQLException
            
    {
        int r=Integer.parseInt(this.txtRazred.getText());
        int o=Integer.parseInt(this.txtOdeljenje.getText());
        System.out.println("Razred je "+r+" Odeljenje je"+o);
        String username=txtUsername.getText();
        
       try{
           if(!txtUsername.getText().equals("") && !txtPassword.getText().equals("") && !txtUsertype.getText().equals("") && !txtIme.getText().equals("") && !txtPrezime.getText().equals("") && !txtDatumRodj.getText().equals("") && !txtPol.getText().equals("") && !txtRazred.getText().equals("") && !txtOdeljenje.getText().equals(""))
         { 
             DBController.require().DodajKorisnika(this.txtUsername.getText(),this.txtPassword.getText(),this.txtUsertype.getText(), this.txtIme.getText(), this.txtPrezime.getText(), this.txtDatumRodj.getText(), this.txtPol.getText());
              DBController.require().DodajStudenta(this.txtUsername.getText(), Integer.parseInt(this.txtRazred.getText()), Integer.parseInt(this.txtOdeljenje.getText()));
         }
         else
         {
        JOptionPane.showMessageDialog(null, "Niste popunili sva polja");
             }
    }
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null,"Greska");
       }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtUsertype = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtDatumRodj = new javax.swing.JTextField();
        txtPol = new javax.swing.JTextField();
        txtRazred = new javax.swing.JTextField();
        txtOdeljenje = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(10, 0, 5, 8));

        txtUsername.setForeground(new java.awt.Color(102, 102, 102));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername);

        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtPassword);

        txtUsertype.setForeground(new java.awt.Color(153, 153, 153));
        txtUsertype.setText("student");
        txtUsertype.setEnabled(false);
        jPanel1.add(txtUsertype);

        txtIme.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtIme);

        txtPrezime.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtPrezime);

        txtDatumRodj.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtDatumRodj);

        txtPol.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtPol);

        txtRazred.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtRazred);

        txtOdeljenje.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtOdeljenje);

        btnSacuvaj.setBackground(new java.awt.Color(124, 187, 0));
        btnSacuvaj.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvaj.setText("SACUVAJ");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(10, 0, 5, 8));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Username:");
        jPanel3.add(jLabel1);

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Lozinka:");
        jPanel3.add(jLabel2);

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Tip korisnika:");
        jPanel3.add(jLabel3);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Ime:");
        jPanel3.add(jLabel4);

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Prezime:");
        jPanel3.add(jLabel5);

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Datum rodjenja:");
        jPanel3.add(jLabel6);

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Pol:");
        jPanel3.add(jLabel7);

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Razred:");
        jPanel3.add(jLabel8);

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Odeljenje:");
        jPanel3.add(jLabel9);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            // TODO add your handling code here:
            DodajStudenta();
            
        } catch (SQLException ex) {
            Logger.getLogger(FrameDodajStudenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDodajStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDodajStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDodajStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDodajStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDodajStudenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDatumRodj;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtOdeljenje;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPol;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtRazred;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsertype;
    // End of variables declaration//GEN-END:variables
}
