/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika;
import SuperMatematika.pnlOdabirTesta.ComboItem;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.SwingConstants;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
/**
 *
 * @author Melida
 */
public class mainChoiceView extends javax.swing.JPanel {
    
    Student trenutniKorisnik;
    public mainChoiceView(Student tk) throws SQLException {
        trenutniKorisnik=tk;
        initComponents();
    }
    public void hoverButton(JButton b) {
        b.setBackground(Color.decode("#F88457"));
        
    }
    public void hoverButtonExit(JButton b) {
        b.setBackground(Color.decode("#F65314"));
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLekcije2 = new javax.swing.JButton();
        btnZadaci = new javax.swing.JButton();
        btnProbniTest = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbRedniBrojTesta = new javax.swing.JComboBox<>();
        cbPredmet = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnZapocniTest = new javax.swing.JButton();

        pnlMainContent.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnLekcije2.setBackground(new java.awt.Color(246, 83, 20));
        btnLekcije2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnLekcije2.setForeground(new java.awt.Color(255, 255, 255));
        btnLekcije2.setText("LEKCIJE");
        btnLekcije2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        btnLekcije2.setFocusPainted(false);
        btnLekcije2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLekcije2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverHandler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeave(evt);
            }
        });
        btnLekcije2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLekcije2ActionPerformed(evt);
            }
        });

        btnZadaci.setBackground(new java.awt.Color(0, 161, 241));
        btnZadaci.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnZadaci.setForeground(new java.awt.Color(255, 255, 255));
        btnZadaci.setText("ZADACI");
        btnZadaci.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        btnZadaci.setFocusPainted(false);
        btnZadaci.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnZadaci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverZadaci(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeaveZadaci(evt);
            }
        });
        btnZadaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZadaciActionPerformed(evt);
            }
        });

        btnProbniTest.setBackground(new java.awt.Color(255, 187, 0));
        btnProbniTest.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnProbniTest.setForeground(new java.awt.Color(255, 255, 255));
        btnProbniTest.setText("PROBNI TEST");
        btnProbniTest.setToolTipText("");
        btnProbniTest.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        btnProbniTest.setFocusPainted(false);
        btnProbniTest.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnProbniTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverProbni(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeaveProbni(evt);
            }
        });
        btnProbniTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbniTestActionPerformed(evt);
            }
        });

        btnTest.setBackground(new java.awt.Color(124, 187, 0));
        btnTest.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnTest.setForeground(new java.awt.Color(255, 255, 255));
        btnTest.setText("TEST");
        btnTest.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        btnTest.setFocusPainted(false);
        btnTest.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverTest(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeaveTest(evt);
            }
        });
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnLekcije2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnZadaci, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnProbniTest, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTest, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLekcije2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZadaci, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProbniTest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        cbRedniBrojTesta.setForeground(new java.awt.Color(102, 102, 102));

        cbPredmet.setForeground(new java.awt.Color(102, 102, 102));
        cbPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPredmetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Predmet:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Redni broj testa:");

        btnZapocniTest.setBackground(new java.awt.Color(124, 187, 0));
        btnZapocniTest.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnZapocniTest.setForeground(new java.awt.Color(255, 255, 255));
        btnZapocniTest.setText("Zapocni test");
        btnZapocniTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapocniTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(79, 79, 79)
                        .addComponent(cbPredmet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnZapocniTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbRedniBrojTesta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(cbRedniBrojTesta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnZapocniTest, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainContentLayout = new javax.swing.GroupLayout(pnlMainContent);
        pnlMainContent.setLayout(pnlMainContentLayout);
        pnlMainContentLayout.setHorizontalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainContentLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(133, 133, 133))
        );
        pnlMainContentLayout.setVerticalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContentLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
@SuppressWarnings("unchecked")
    private void btnLekcije2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLekcije2ActionPerformed
         // TODO add your handling code here:
        pnlBirajPredmet newPnl;
       try {
            newPnl = new pnlBirajPredmet(trenutniKorisnik,DBController.require().getPredmete(trenutniKorisnik.getRazred()),"predavanja");
//            newPnl = new pnlBirajRazred(trenutniKorisnik,"predavanja");
            this.removeAll();
            this.revalidate();
            this.setLayout(new BorderLayout());
            this.add(newPnl);
            
       } catch (Exception ex) {
           Logger.getLogger(StudentFrame.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnLekcije2ActionPerformed

    private void btnZadaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZadaciActionPerformed
        pnlBirajPredmet newPnl;
        try {
            newPnl = new pnlBirajPredmet(trenutniKorisnik,DBController.require().getPredmete(trenutniKorisnik.getRazred()),"zadaci");
          //  newPnl = new pnlBirajRazred(trenutniKorisnik,"zadaci");
            this.removeAll();
            this.revalidate();
            this.setLayout(new BorderLayout());
            this.add(newPnl);
        } catch (Exception ex) {
            Logger.getLogger(mainChoiceView.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btnZadaciActionPerformed

    private void btnProbniTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbniTestActionPerformed
        pnlBiranjeOblastiZaProbniTest newPnl=new pnlBiranjeOblastiZaProbniTest(trenutniKorisnik);
        this.removeAll();
        this.revalidate();
        this.setLayout(new BorderLayout());
        this.add(newPnl);
    }//GEN-LAST:event_btnProbniTestActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        pnlOdabirTesta newPnl=new pnlOdabirTesta(trenutniKorisnik);
        this.removeAll();
        this.revalidate();
        this.setLayout(new BorderLayout());
        this.add(newPnl);
    }//GEN-LAST:event_btnTestActionPerformed

    private void HoverHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverHandler
        // TODO add your handling code here:
        hoverButton((JButton) evt.getSource());
    }//GEN-LAST:event_HoverHandler

    private void HoverLeave(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverLeave
        // TODO add your handling code here:
          hoverButtonExit((JButton) evt.getSource());
    }//GEN-LAST:event_HoverLeave

    private void HoverZadaci(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverZadaci
        // TODO add your handling code here:
        this.btnZadaci.setBackground(Color.decode("#38BCFF"));
       
        
    }//GEN-LAST:event_HoverZadaci

    private void HoverProbni(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverProbni
        // TODO add your handling code here:
         this.btnProbniTest.setBackground(Color.decode("#FFD76B"));
    }//GEN-LAST:event_HoverProbni

    private void HoverTest(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverTest
        // TODO add your handling code here:
        this.btnTest.setBackground(Color.decode("#8ED600"));
    }//GEN-LAST:event_HoverTest

    private void HoverLeaveZadaci(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverLeaveZadaci
        // TODO add your handling code here:
        this.btnZadaci.setBackground(Color.decode("#00A1F1"));
    }//GEN-LAST:event_HoverLeaveZadaci

    private void HoverLeaveProbni(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverLeaveProbni
        // TODO add your handling code here:FFBB00
         this.btnProbniTest.setBackground(Color.decode("#FFBB00"));
    }//GEN-LAST:event_HoverLeaveProbni

    private void HoverLeaveTest(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverLeaveTest
        // TODO add your handling code here:7CBB00
        this.btnTest.setBackground(Color.decode("#7CBB00"));
    }//GEN-LAST:event_HoverLeaveTest

    private void cbPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPredmetActionPerformed
        cbRedniBrojTesta.removeAllItems();

        String upit =  "SELECT redni_broj_testa FROM Test WHERE predmet = " + ((ComboItem)cbPredmet.getSelectedItem()).getValue() +
        " AND razred = " + trenutniKorisnik.getRazred() +
        " AND odeljenje = " + trenutniKorisnik.getOdeljenje() + ";";

        try {
            ResultSet rezultat = DBController.require().submitQuery(upit);
            while(rezultat.next()) {
                cbRedniBrojTesta.addItem(rezultat.getString("redni_broj_testa"));
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(OcenePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbPredmetActionPerformed

    private void btnZapocniTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapocniTestActionPerformed
        if (cbRedniBrojTesta.getItemCount() != 0) {
            int ID_predmeta = Integer.parseInt(((ComboItem)cbPredmet.getSelectedItem()).getValue());
            int redniBrojTesta = Integer.parseInt(cbRedniBrojTesta.getSelectedItem().toString());
            pnlTest newPnl=new pnlTest(trenutniKorisnik, ID_predmeta, redniBrojTesta);
            this.removeAll();
            this.revalidate();
            this.setLayout(new BorderLayout());
            this.add(newPnl);
        }
        else
        JOptionPane.showMessageDialog(this, "Nema testova za dati predmet");
    }//GEN-LAST:event_btnZapocniTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLekcije2;
    private javax.swing.JButton btnProbniTest;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnZadaci;
    private javax.swing.JButton btnZapocniTest;
    private javax.swing.JComboBox<ComboItem> cbPredmet;
    private javax.swing.JComboBox<String> cbRedniBrojTesta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlMainContent;
    // End of variables declaration//GEN-END:variables
}
