/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika;
import java.awt.BorderLayout;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTree;
import javax.swing.SwingConstants;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
/**
 *
 * @author Melida
 */
public class mainChoiceView extends javax.swing.JPanel {
    
    Student trenutniKorisnik;
    public mainChoiceView(Student tk) throws SQLException {
        trenutniKorisnik=tk;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainContent = new javax.swing.JPanel();
        btnLekcije2 = new javax.swing.JButton();
        btnLekcije1 = new javax.swing.JButton();
        btnLekcije3 = new javax.swing.JButton();
        btnProbni = new javax.swing.JButton();

        pnlMainContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLekcije2.setBackground(new java.awt.Color(255, 204, 102));
        btnLekcije2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnLekcije2.setForeground(new java.awt.Color(255, 255, 255));
        btnLekcije2.setText("LEKCIJE");
        btnLekcije2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnLekcije2.setFocusPainted(false);
        btnLekcije2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLekcije2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLekcije2ActionPerformed(evt);
            }
        });
        pnlMainContent.add(btnLekcije2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 200, 180));

        btnLekcije1.setBackground(new java.awt.Color(255, 204, 102));
        btnLekcije1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnLekcije1.setForeground(new java.awt.Color(255, 255, 255));
        btnLekcije1.setText("ZADACI");
        btnLekcije1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnLekcije1.setFocusPainted(false);
        btnLekcije1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLekcije1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLekcije1ActionPerformed(evt);
            }
        });
        pnlMainContent.add(btnLekcije1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 200, 180));

        btnLekcije3.setBackground(new java.awt.Color(255, 204, 102));
        btnLekcije3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnLekcije3.setForeground(new java.awt.Color(255, 255, 255));
        btnLekcije3.setText("PROBNI TEST");
        btnLekcije3.setToolTipText("");
        btnLekcije3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnLekcije3.setFocusPainted(false);
        btnLekcije3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLekcije3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLekcije3ActionPerformed(evt);
            }
        });
        pnlMainContent.add(btnLekcije3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 200, 180));

        btnProbni.setBackground(new java.awt.Color(255, 204, 102));
        btnProbni.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnProbni.setForeground(new java.awt.Color(255, 255, 255));
        btnProbni.setText("TEST");
        btnProbni.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnProbni.setFocusPainted(false);
        btnProbni.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnProbni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbniActionPerformed(evt);
            }
        });
        pnlMainContent.add(btnProbni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 200, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
@SuppressWarnings("unchecked")
    private void btnLekcije2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLekcije2ActionPerformed
         // TODO add your handling code here:
        pnlBirajPredmet newPnl;
       try {
            newPnl = new pnlBirajPredmet(trenutniKorisnik,DBController.require().getPredmete(trenutniKorisnik.getRazred()),"predavanja");
//            newPnl = new pnlBirajRazred(trenutniKorisnik,"predavanja");
            this.removeAll();
            this.revalidate();
            this.setLayout(new BorderLayout());
            this.add(newPnl);
       } catch (Exception ex) {
           Logger.getLogger(StudentFrame.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnLekcije2ActionPerformed

    private void btnLekcije1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLekcije1ActionPerformed
        pnlBirajPredmet newPnl;
        try {
            newPnl = new pnlBirajPredmet(trenutniKorisnik,DBController.require().getPredmete(trenutniKorisnik.getRazred()),"zadaci");
          //  newPnl = new pnlBirajRazred(trenutniKorisnik,"zadaci");
            this.removeAll();
            this.revalidate();
            this.setLayout(new BorderLayout());
            this.add(newPnl);
        } catch (Exception ex) {
            Logger.getLogger(mainChoiceView.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btnLekcije1ActionPerformed

    private void btnLekcije3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLekcije3ActionPerformed
        pnlBiranjeOblastiZaProbniTest newPnl=new pnlBiranjeOblastiZaProbniTest(trenutniKorisnik);
        this.removeAll();
        this.revalidate();
        this.setLayout(new BorderLayout());
        this.add(newPnl);
    }//GEN-LAST:event_btnLekcije3ActionPerformed

    private void btnProbniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbniActionPerformed
        pnlOdabirTesta newPnl=new pnlOdabirTesta(trenutniKorisnik);
        this.removeAll();
        this.revalidate();
        this.setLayout(new BorderLayout());
        this.add(newPnl);
    }//GEN-LAST:event_btnProbniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLekcije1;
    private javax.swing.JButton btnLekcije2;
    private javax.swing.JButton btnLekcije3;
    private javax.swing.JButton btnProbni;
    private javax.swing.JPanel pnlMainContent;
    // End of variables declaration//GEN-END:variables
}
