/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika;

import java.awt.BorderLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melida
 */
public class PanelSviProfesori extends javax.swing.JPanel {

    /**
     * Creates new form PanelSviProfesori
     */
    
    public PanelSviProfesori() {
        initComponents();
        popuniTabelu();
    }
   public void popuniTabelu()
   {
       
       String upit="Select Users.username,Users.ime,Users.prezime,Users.godina_rodjenja,Users.pol,Nastavnik.fakultet from Users,Nastavnik where Users.username=Nastavnik.username";
         try {
            ResultSet rezultat = DBController.require().submitQuery(upit);
            while(rezultat.next()) {
                Object[] row = { rezultat.getString("Username"), rezultat.getString("Ime"), rezultat.getString("Prezime"),rezultat.getString("Godina_rodjenja"),rezultat.getString("Pol"),rezultat.getString("fakultet")}
                        ;
                ((DefaultTableModel) jTable1.getModel()).insertRow(0, row);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(OcenePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
   public void izbrisiIzTabele() throws SQLException
   {   
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnIzbrisi = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        pnlMainContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainContent.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Ime", "Prezime", "Godina rodjenja", "Pol", "Fakultet"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        btnIzbrisi.setBackground(new java.awt.Color(124, 187, 0));
        btnIzbrisi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnIzbrisi.setForeground(new java.awt.Color(255, 255, 255));
        btnIzbrisi.setText("Izbrisi");
        btnIzbrisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnIzbrisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIzbrisiClick(evt);
            }
        });
        btnIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiActionPerformed(evt);
            }
        });

        btnDodaj.setBackground(new java.awt.Color(124, 187, 0));
        btnDodaj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDodaj.setForeground(new java.awt.Color(255, 255, 255));
        btnDodaj.setText("Dodaj ");
        btnDodaj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPrikazi.setBackground(new java.awt.Color(124, 187, 0));
        btnPrikazi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrikazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikazi.setText("Prikazi");
        btnPrikazi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(124, 187, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Izmeni");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainContentLayout = new javax.swing.GroupLayout(pnlMainContent);
        pnlMainContent.setLayout(pnlMainContentLayout);
        pnlMainContentLayout.setHorizontalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContentLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrikazi, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(btnIzbrisi, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlMainContentLayout.setVerticalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
            .addGroup(pnlMainContentLayout.createSequentialGroup()
                .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnIzbrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiActionPerformed
        int niz[]=new int[this.jTable1.getSelectedRowCount()];
        niz=this.jTable1.getSelectedRows();
        
        for(int i=0;i<niz.length;i++){
            try {
                System.out.println(this.jTable1.getModel().getValueAt(niz[i], 0));
                DBController.require().izbrisiKorisnika(this.jTable1.getModel().getValueAt(niz[i], 0));
                ((DefaultTableModel)this.jTable1.getModel()).removeRow(niz[i]);
            } catch (SQLException ex) {
                Logger.getLogger(PanelSviProfesori.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnIzbrisiActionPerformed

    private void btnIzbrisiClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzbrisiClick
        try {
            izbrisiIzTabele();
        } catch (SQLException ex) {
            Logger.getLogger(PanelSviProfesori.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIzbrisiClick

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        Navigacija.PromeniPanel(this.pnlMainContent, new PanelSviProfesori());
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
       FrameDodajProfesora fds;
        try {
            fds = new FrameDodajProfesora();
              fds.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PanelSviProfesori.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btnDodajActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlMainContent;
    // End of variables declaration//GEN-END:variables

    private Object DBController() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
