/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika;

import java.awt.BorderLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samed
 */
public class pnlOdabirTesta extends javax.swing.JPanel {

    private Student trenutniKorisnik;
    public pnlOdabirTesta(Student k) {
        trenutniKorisnik = k;
        
        initComponents();
        popuniCBPredmeti();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cbPredmet = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnZapocniTest = new javax.swing.JButton();
        cbRedniBrojTesta = new javax.swing.JComboBox<>();

        jLabel3.setText("jLabel3");

        cbPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPredmetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ovo je samo u test svrhe");

        jLabel2.setText("Predmet");

        jLabel4.setText("Redni broj testa");

        btnZapocniTest.setText("Zapocni test");
        btnZapocniTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapocniTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(cbPredmet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnZapocniTest)
                            .addComponent(cbRedniBrojTesta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbRedniBrojTesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnZapocniTest)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnZapocniTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapocniTestActionPerformed
        if (cbRedniBrojTesta.getItemCount() != 0) {
            int ID_predmeta = Integer.parseInt(((ComboItem)cbPredmet.getSelectedItem()).getValue());
            int redniBrojTesta = Integer.parseInt(cbRedniBrojTesta.getSelectedItem().toString());
            pnlTest newPnl=new pnlTest(trenutniKorisnik, ID_predmeta, redniBrojTesta);
            this.removeAll();
            this.revalidate();
            this.setLayout(new BorderLayout());
            this.add(newPnl);
        }
        else
            JOptionPane.showMessageDialog(this, "Nema testova za dati predmet");         
    }//GEN-LAST:event_btnZapocniTestActionPerformed

    private void cbPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPredmetActionPerformed
        cbRedniBrojTesta.removeAllItems();
        
        String upit =  "SELECT redni_broj_testa FROM Test WHERE predmet = " + ((ComboItem)cbPredmet.getSelectedItem()).getValue() +
                " AND razred = " + trenutniKorisnik.getRazred() + 
                " AND odeljenje = " + trenutniKorisnik.getOdeljenje() + ";";
        
        try {
            ResultSet rezultat = DBController.require().submitQuery(upit);
            while(rezultat.next()) {
                cbRedniBrojTesta.addItem(rezultat.getString("redni_broj_testa"));
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(OcenePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbPredmetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZapocniTest;
    private javax.swing.JComboBox<ComboItem> cbPredmet;
    private javax.swing.JComboBox<String> cbRedniBrojTesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void popuniCBPredmeti() {
        String upit = "SELECT Predmet.Naziv, Predmet.ID_predmeta " +
                      "FROM Users INNER JOIN ((Nastavnik INNER JOIN Predmet ON Nastavnik.username = Predmet.Username_nastavnika) INNER JOIN SlusaPredmet ON Predmet.ID_predmeta = SlusaPredmet.ID_predmeta) ON Users.Username = Nastavnik.username\n" +
                      "WHERE SlusaPredmet.Username_ucenik=\"" + trenutniKorisnik.getUsername() + "\";";
         try {
            ResultSet rezultat = DBController.require().submitQuery(upit);
            while(rezultat.next()) {
                cbPredmet.addItem(new ComboItem(rezultat.getString("Naziv"), rezultat.getString("ID_predmeta")));
            }
        } catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(OcenePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    // Mala pomocna klasa, mozda bolje da je u posebnom fajlu
    class ComboItem
    {
        private String key;
        private String value;

        public ComboItem(String key, String value)
        {
            this.key = key;
            this.value = value;
        }

        @Override
        public String toString()
        {
            return key;
        }

        public String getKey()
        {
            return key;
        }

        public String getValue()
        {
            return value;
        }
    }
}
