/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import static javax.swing.text.StyleConstants.Bold;
import static javax.swing.text.StyleConstants.Size;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author 1
 */
public class pnlPredavanja extends javax.swing.JPanel {

    /**
     * Creates new form pnlPredavanja
     */
    Student trenutniKorisnik;
    Predmet trenutniPredmet;
    ArrayList<String> listaPutanja = new ArrayList();
    ArrayList<String> listaLekcija = new ArrayList();
    ArrayList<JButton> listaButtona = new ArrayList();

    public pnlPredavanja(Student tk,Predmet pk) throws SQLException {
        trenutniPredmet=pk;
        trenutniKorisnik=tk;
        initComponents();
        listaPutanja=DBController.require().getPutanjeOblasti("Lekcija",pk.getId());
        listaLekcija=DBController.require().getOblasti("Lekcija",pk.getId());
        createForm();
//        loadLekcije();

    }

    private void createForm() {
        this.removeAll();
        this.revalidate();
        this.setLayout(new GridLayout(listaLekcija.size()<6?6:listaLekcija.size()+1, 0));
        System.out.println(listaLekcija.size());
        Font f = new Font("Arial", Font.ITALIC, 24);
            this.add(btnBaack);
        for (int i = 0; i < listaLekcija.size(); i++) {
            JButton b = new JButton(listaLekcija.get(i));
            b.setBackground(Color.white);
            b.setBorder(BorderFactory.createSoftBevelBorder(1, Color.darkGray, Color.lightGray));
            b.setPreferredSize(new Dimension(40, 40));
            b.setFont(f);

            b.setFocusPainted(false);

            b.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    showPdf(evt);
                }

            }
            );

            listaButtona.add(b);
            this.add(b);
            this.setVisible(true);
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBaack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBaack.setBackground(new java.awt.Color(102, 102, 102));
        btnBaack.setText("Back");
        btnBaack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaackActionPerformed(evt);
            }
        });
        add(btnBaack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaackActionPerformed
        pnlBirajPredmet main;
        try {
            main = new pnlBirajPredmet(trenutniKorisnik,DBController.require().getPredmete(trenutniPredmet.getRazred()),"predavanja");
            this.removeAll();
            this.revalidate();
            this.setLayout(new BorderLayout());
            this.add(main);
        } catch (Exception ex) {

        } // TODO add your handling code here:
    }//GEN-LAST:event_btnBaackActionPerformed

    private void showPdf(java.awt.event.ActionEvent evt) {
        String putanja = null;
        for (int i = 0; i < this.listaButtona.size(); i++) {
            if (evt.getSource() == this.listaButtona.get(i)) {
                putanja = listaPutanja.get(i);
                break;
            }
        }
        pnlPDFView newPnl = new pnlPDFView(trenutniKorisnik,trenutniPredmet,putanja, "predavanja");
        this.removeAll();
        this.revalidate();
        this.setLayout(new BorderLayout());
        this.add(newPnl);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaack;
    // End of variables declaration//GEN-END:variables
}
