/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import static javax.swing.text.StyleConstants.Bold;
import static javax.swing.text.StyleConstants.Size;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author 1
 */
public class pnlPredavanja extends javax.swing.JPanel {

    /**
     * Creates new form pnlPredavanja
     */
    Connection connection=null;
    Statement statement=null;
    ResultSet resultSet=null;
    int razred;
    String username;
    ArrayList<String> listaPutanja=new ArrayList();
    ArrayList<String> listaLekcija=new ArrayList();
    ArrayList<JButton> listaButtona=new ArrayList();
    public pnlPredavanja(Connection cnc,Statement st,ResultSet rs,int rzrd,String un) throws SQLException {
        initComponents();
         razred=rzrd;
         connection=cnc;
         statement=st;
         resultSet=rs;
         username=un;
        loadLekcije();
        
    }
    private void createForm(){
        this.btnHolder.removeAll();
        this.btnHolder.revalidate();
        this.btnHolder.setLayout(new GridLayout(4,0));
        System.out.println(listaLekcija.size());
          Font f = new Font("Arial", Font.ITALIC, 24);
        for(int i=0;i<listaLekcija.size();i++){
            JButton b=new JButton(listaLekcija.get(i));
            b.setBackground(Color.white);
            b.setBorder(BorderFactory.createSoftBevelBorder(1, Color.darkGray, Color.lightGray));
            b.setPreferredSize(new Dimension(40,40));
            b.setFont(f);
            
            b.setFocusPainted(false);
            
            b.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    showPdf(evt);
                }
                
            }
            );
            
            listaButtona.add(b);
            this.btnHolder.add(b);
            this.btnHolder.add(btnBaack);
            this.btnHolder.setVisible(true);
        }
      
    }
    
    
       
    
    private void loadLekcije(){
        try {

            // Step 2.B: Creating JDBC Statement 
            statement = (Statement) connection.createStatement();  
            resultSet = statement.executeQuery("SELECT NaslovLekcije,Putanja from Lekcija where Razred='"+ razred+"';");
            
            // Step 2.C: Executing SQL & retrieve data into ResultSet
             try{
                 while(resultSet.next()){
                     listaPutanja.add(resultSet.getString("Putanja"));
                     listaLekcija.add(resultSet.getString("NaslovLekcije"));
                     
                 }
                
             }       
             catch(Exception e){
                 System.out.println(e);
             }
            // processing returned data and printing into console
          
        }
        catch(Exception E){
            System.out.println(E);
        }
        finally {

            // Step 3: Closing database connection
            try {
                if(null != connection) {

                    // cleanup resources, once after 
                    statement.close();

                    //connection.close();
                }
            }
            catch (SQLException sqlex) {
                sqlex.printStackTrace();
            }
            
        createForm(); 
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHolder = new javax.swing.JPanel();
        btnBaack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHolder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBaack.setBackground(new java.awt.Color(102, 102, 102));
        btnBaack.setText("Back");
        btnBaack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaackActionPerformed(evt);
            }
        });
        btnHolder.add(btnBaack, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 90, 60));

        add(btnHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaackActionPerformed
         mainChoiceView main;
        try{
            main=new mainChoiceView(connection,statement,resultSet,razred,username);
        this.removeAll();
        this.revalidate();
        this.setLayout(new BorderLayout());
        this.add(main);
        }
        catch(Exception ex)
        {
            
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnBaackActionPerformed

    private void showPdf(java.awt.event.ActionEvent evt) {                         
            String putanja=null;
            for(int i=0;i<this.listaButtona.size();i++){
                if(evt.getSource()==this.listaButtona.get(i)){
                    putanja=listaPutanja.get(i);
                    break;
                }
            }
            pnlPDFView newPnl=new pnlPDFView(connection,statement,resultSet,razred,putanja,username);
            this.removeAll();
            this.revalidate();
            this.setLayout(new BorderLayout());
            this.add(newPnl);
        }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaack;
    private javax.swing.JPanel btnHolder;
    // End of variables declaration//GEN-END:variables
}
