/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;

/**
 *
 * @author 1
 */
public class pnlZadaci extends javax.swing.JPanel {
    Student trenutniKorisnik;
    Predmet trenutniPredmet;
    ArrayList<String> listaPutanja=new ArrayList();
    ArrayList<String> listaOblasti=new ArrayList();
    ArrayList<JButton> listaButtona=new ArrayList();
    public pnlZadaci(Student tr,Predmet pk) throws SQLException {
        trenutniPredmet=pk;
        trenutniKorisnik=tr;
        initComponents();
        listaPutanja=DBController.require().getPutanjeOblasti("Vezbe",pk.getId());
        listaOblasti=DBController.require().getOblasti("Vezbe",pk.getId());
        createForm();
    }
    private void createForm(){
        this.removeAll();
        this.revalidate();
        this.setLayout(new GridLayout(listaOblasti.size()<6?6:listaOblasti.size()+1,0));
        System.out.println(listaOblasti.size());
          Font f = new Font("Arial", Font.ITALIC, 24);
        this.add(this.btnBack);
        for(int i=0;i<listaOblasti.size();i++){
            JButton b=new JButton(listaOblasti.get(i));
            b.setBackground(Color.white);
            b.setBorder(BorderFactory.createSoftBevelBorder(1, Color.darkGray, Color.lightGray));
            b.setPreferredSize(new Dimension(40,40));
            b.setFont(f);
            
            b.setFocusPainted(false);
            
            b.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    showPdf(evt);
                }
                
            }
            );
            
            listaButtona.add(b);
            this.add(b);
            this.setVisible(true);
        }
      
    }
    
    
       
     private void showPdf(java.awt.event.ActionEvent evt) {                         
            String putanja=null;
            for(int i=0;i<this.listaButtona.size();i++){
                if(evt.getSource()==this.listaButtona.get(i)){
                    putanja=listaPutanja.get(i);
                    break;
                }
            }
            pnlPDFView newPnl=new pnlPDFView(trenutniKorisnik,trenutniPredmet,putanja,"zadaci");
            this.removeAll();
            this.revalidate();
            this.setLayout(new BorderLayout());
            this.add(newPnl);
        }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        btnBack.setText("back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnBack))
                .addGap(243, 243, 243))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         pnlBirajPredmet main;
        try{
            main=new pnlBirajPredmet(trenutniKorisnik,DBController.require().getPredmete(trenutniPredmet.getRazred()),"zadaci");
        this.removeAll();
        this.revalidate();
        this.setLayout(new BorderLayout());
        this.add(main);
        }
        catch(Exception ex)
        {
            
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
