/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTree;
import javax.swing.SwingConstants;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Melida
 */
public class StudentFrame extends javax.swing.JFrame {
    Student trenutniKorisnik;

    public StudentFrame(Korisnik k) throws SQLException {
        initComponents();
        
        this.trenutniKorisnik=new Student(k);
        System.out.println(trenutniKorisnik);
        trenutniKorisnik.setRazred(DBController.require().getRazred(trenutniKorisnik));
        this.lblRazred.setText(trenutniKorisnik.getRazred() + ".");
        System.out.println(trenutniKorisnik.getIme());
        this.imePrezime.setText(trenutniKorisnik.getIme()+" "+trenutniKorisnik.getPrezime());
        
        mainChoiceView newPnl = new mainChoiceView(trenutniKorisnik);
        this.pnlMainContent.removeAll();
        this.pnlMainContent.revalidate();
        this.pnlMainContent.setLayout(new BorderLayout());
        this.pnlMainContent.add(newPnl);
        
        setNav();
        this.pnlProfilMenu.setVisible(false);
    }


//    

    public void setNav() {
        //create the root node
        DefaultMutableTreeNode category = new DefaultMutableTreeNode("Navigacija");
        DefaultMutableTreeNode category1 = new DefaultMutableTreeNode("V Razred");
        //create the child nodes
        DefaultMutableTreeNode category1_1 = new DefaultMutableTreeNode("Skupovi");
        DefaultMutableTreeNode category1_2 = new DefaultMutableTreeNode("Deljivost brojeva");
        //add the child nodes to the root node
        category1.add(category1_1);
        category1.add(category1_2);
        category.add(category1);
        DefaultTreeModel defaultTreeModel = new DefaultTreeModel(category);
        

    }

    public void hoverButton(JButton b) {
        b.setBackground(Color.decode("#00A1F1"));
        
    }

    public void hoverButtonExit(JButton b) {
        b.setBackground(Color.decode("#0073AD"));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        imePrezime = new javax.swing.JLabel();
        lblRazred = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlMainContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlProfilMenu = new javax.swing.JPanel();
        btnProfil = new javax.swing.JButton();
        btnOcene = new javax.swing.JButton();
        btnOdjava = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(0, 115, 173));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imePrezime.setBackground(new java.awt.Color(255, 255, 255));
        imePrezime.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        imePrezime.setForeground(new java.awt.Color(255, 255, 255));
        imePrezime.setText("Ime Prezime");
        pnlHeader.add(imePrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        lblRazred.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        lblRazred.setForeground(new java.awt.Color(255, 255, 255));
        lblRazred.setText("-");
        pnlHeader.add(lblRazred, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 50, 40));

        btnMenu.setBackground(new java.awt.Color(0, 115, 173));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlikeDizajn/MenuIcon.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setFocusPainted(false);
        btnMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MouseDragger(evt);
            }
        });
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseDragger(evt);
            }
        });
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMenu(evt);
            }
        });
        pnlHeader.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jButton1.setBackground(new java.awt.Color(0, 115, 173));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlikeDizajn/homeIcon.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlHeader.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 90, 60));

        pnlBackground.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 60));

        pnlMainContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlBackground.add(pnlMainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 860, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProfilMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlProfilMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlProfilMenu.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        pnlProfilMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProfil.setBackground(new java.awt.Color(0, 115, 173));
        btnProfil.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnProfil.setForeground(new java.awt.Color(255, 255, 255));
        btnProfil.setText("Profil");
        btnProfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnProfil.setFocusPainted(false);
        btnProfil.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfilClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverHandler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeave(evt);
            }
        });
        btnProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilActionPerformed(evt);
            }
        });
        pnlProfilMenu.add(btnProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 50));

        btnOcene.setBackground(new java.awt.Color(0, 115, 173));
        btnOcene.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnOcene.setForeground(new java.awt.Color(255, 255, 255));
        btnOcene.setText("Ocene");
        btnOcene.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnOcene.setFocusPainted(false);
        btnOcene.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnOcene.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverHandler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeave(evt);
            }
        });
        btnOcene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOceneActionPerformed(evt);
            }
        });
        pnlProfilMenu.add(btnOcene, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, 50));

        btnOdjava.setBackground(new java.awt.Color(0, 115, 173));
        btnOdjava.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnOdjava.setForeground(new java.awt.Color(255, 255, 255));
        btnOdjava.setText("Log out");
        btnOdjava.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnOdjava.setFocusPainted(false);
        btnOdjava.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnOdjava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverHandler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeave(evt);
            }
        });
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });
        pnlProfilMenu.add(btnOdjava, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 50));

        jPanel1.add(pnlProfilMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 350));

        pnlBackground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 280, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilActionPerformed
        ProfilPanel newPnl = new ProfilPanel(trenutniKorisnik);
        this.pnlMainContent.removeAll();
        this.pnlMainContent.revalidate();
        this.pnlMainContent.setLayout(new BorderLayout());
        this.pnlMainContent.add(newPnl);
    }//GEN-LAST:event_btnProfilActionPerformed

    private void HoverHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverHandler
        hoverButton((JButton) evt.getSource());
    }//GEN-LAST:event_HoverHandler

    private void HoverLeave(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverLeave
        // TODO add your handling code here:
        hoverButtonExit((JButton) evt.getSource());
    }//GEN-LAST:event_HoverLeave

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        try {
            MainFrame m = new MainFrame();
            m.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(StudentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void showMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMenu
        this.pnlProfilMenu.setVisible(pnlProfilMenu.isVisible() ? false : true);
    }//GEN-LAST:event_showMenu

    private void MouseDragger(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseDragger
        this.pnlProfilMenu.setVisible(pnlProfilMenu.isVisible() ? false : true);  // TODO add your handling code here:
    }//GEN-LAST:event_MouseDragger

    private void btnProfilClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfilClick
        // TODO add your handling code here:
        ProfilPanel newPnl = new ProfilPanel(trenutniKorisnik);
        this.pnlMainContent.removeAll();
        this.pnlMainContent.revalidate();
        this.pnlMainContent.setLayout(new BorderLayout());
        this.pnlMainContent.add(newPnl);
    }//GEN-LAST:event_btnProfilClick

    private void btnOceneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOceneActionPerformed
       
        // TODO add your handling code here:
        OcenePanel newPnl = new OcenePanel(trenutniKorisnik);
        this.pnlMainContent.removeAll();
        this.pnlMainContent.revalidate();
        this.pnlMainContent.setLayout(new BorderLayout());
        this.pnlMainContent.add(newPnl);
    }//GEN-LAST:event_btnOceneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         mainChoiceView main;
        try {
            main = new mainChoiceView(trenutniKorisnik);
            this.pnlMainContent.removeAll();
            this.pnlMainContent.revalidate();
            this.pnlMainContent.setLayout(new BorderLayout());
            this.pnlMainContent.add(main);
        } catch (Exception ex) {

        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new StudentFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnOcene;
    private javax.swing.JButton btnOdjava;
    private javax.swing.JButton btnProfil;
    private javax.swing.JLabel imePrezime;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRazred;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMainContent;
    private javax.swing.JPanel pnlProfilMenu;
    // End of variables declaration//GEN-END:variables
}
