/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika.TehnoloskiVisak;

import SuperMatematika.ZajednickeKlase.DBController;
import SuperMatematika.UcenikPaneli.PanelUcenikMainChoice;
import SuperMatematika.UcenikPaneli.PanelBirajPredmet;
import SuperMatematika.Model.Student;
import SuperMatematika.ZajednickeKlase.Navigacija;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;

/**
 *
 * @author 1
 */
public class pnlBirajRazred extends javax.swing.JPanel {

    Student trenutniKorisnik;
    ArrayList<JButton> listaButtona = new ArrayList();
    String prethodnik;

    public pnlBirajRazred(Student s, String prethodno) {
        trenutniKorisnik = s;
        prethodnik = prethodno;
        initComponents();
        createForm();
    }

    private void createForm() {
        this.removeAll();
        this.revalidate();
        this.setLayout(new GridLayout(5, 0));
        this.add(btnBack);
        Font f = new Font("Arial", Font.ITALIC, 24);
        for (int i = 5; i <= 8; i++) {
            System.out.println("asd");
            JButton b = new JButton(i + " Razred");
            b.setBackground(Color.white);
            b.setBorder(BorderFactory.createSoftBevelBorder(1, Color.darkGray, Color.lightGray));
            b.setPreferredSize(new Dimension(40, 40));
            b.setFont(f);

            b.setFocusPainted(false);
            int razred = i;
            b.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    prikaziPredmete(razred);
                }

            }
            );

            listaButtona.add(b);
            this.add(b);
            this.setVisible(true);
        }

    }

    private void prikaziPredmete(int razred) {
        PanelBirajPredmet main;
        try {
            main = new PanelBirajPredmet(trenutniKorisnik, DBController.require().getPredmete(razred), prethodnik);
            Navigacija.PromeniPanel(this, main);
        } catch (Exception ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(0, 345, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnBack)
                .addContainerGap(285, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            Navigacija.PromeniPanel(this, new PanelUcenikMainChoice(trenutniKorisnik));
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    // End of variables declaration//GEN-END:variables
}
