/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika.ProfesorPaneli;

import SuperMatematika.ZajednickeKlase.DBController;
import SuperMatematika.Main.MainFrame;
import SuperMatematika.ZajednickeKlase.Navigacija;
import SuperMatematika.ZajednickeKlase.PanelPromenaLozinke;
import SuperMatematika.Model.Predmet;
import SuperMatematika.Model.Profesor;
import SuperMatematika.UcenikPaneli.FrameUcenik;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Melida
 */
public class FrameProfesor extends javax.swing.JFrame {

    Profesor trenutniKorisnik;
    ArrayList<Predmet> listaPredmeta = new ArrayList();

    public FrameProfesor(Profesor tk) throws SQLException {
        trenutniKorisnik = tk;
        initComponents();
        listaPredmeta = DBController.require().getProfPredmeti(trenutniKorisnik);

        listaPredmeta.forEach(e -> {
            System.out.println(e.getNazivPredmeta());
        });

        this.imePrezime.setText(trenutniKorisnik.getIme() + " " + trenutniKorisnik.getPrezime());

        Navigacija.PromeniPanel(this.pnlMainContent, new PanelProfesorMainChoice(trenutniKorisnik));

    }

    public void hoverButton(JButton b) {
        b.setBackground(Color.decode("#00A1F1"));

    }

    public void hoverButtonExit(JButton b) {
        b.setBackground(Color.decode("#0073AD"));

    }

    private FrameProfesor() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnlBackground = new javax.swing.JPanel();
        ProfesorViewLeft = new javax.swing.JPanel();
        imePrezime = new javax.swing.JLabel();
        btnProfil = new javax.swing.JButton();
        btnSastaviTest = new javax.swing.JButton();
        btnRezultatiTesta = new javax.swing.JButton();
        btnIzvestaj = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnPocetna = new javax.swing.JButton();
        btnPodesavanja = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pnlMainContent = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackground.setPreferredSize(new java.awt.Dimension(1140, 710));

        ProfesorViewLeft.setBackground(new java.awt.Color(0, 115, 173));
        ProfesorViewLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        imePrezime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        imePrezime.setForeground(new java.awt.Color(255, 255, 255));
        imePrezime.setText("IME I PREZIME");

        btnProfil.setBackground(new java.awt.Color(124, 187, 0));
        btnProfil.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnProfil.setForeground(new java.awt.Color(255, 255, 255));
        btnProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlikeDizajn/ProfilIcon.png"))); // NOI18N
        btnProfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnProfil.setFocusPainted(false);
        btnProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverHandler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeave(evt);
            }
        });
        btnProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilActionPerformed(evt);
            }
        });

        btnSastaviTest.setBackground(new java.awt.Color(0, 115, 173));
        btnSastaviTest.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnSastaviTest.setForeground(new java.awt.Color(255, 255, 255));
        btnSastaviTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlikeDizajn/Test.png"))); // NOI18N
        btnSastaviTest.setText("Sastavi test");
        btnSastaviTest.setBorder(null);
        btnSastaviTest.setFocusPainted(false);
        btnSastaviTest.setIconTextGap(19);
        btnSastaviTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSastaviTestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverHandler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeave(evt);
            }
        });
        btnSastaviTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSastaviTestActionPerformed(evt);
            }
        });

        btnRezultatiTesta.setBackground(new java.awt.Color(0, 115, 173));
        btnRezultatiTesta.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnRezultatiTesta.setForeground(new java.awt.Color(255, 255, 255));
        btnRezultatiTesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlikeDizajn/OceneIcon.png"))); // NOI18N
        btnRezultatiTesta.setText("Rezultati");
        btnRezultatiTesta.setAlignmentY(0.0F);
        btnRezultatiTesta.setBorder(null);
        btnRezultatiTesta.setFocusPainted(false);
        btnRezultatiTesta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRezultatiTesta.setIconTextGap(30);
        btnRezultatiTesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverHandler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeave(evt);
            }
        });
        btnRezultatiTesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRezultatiTestaActionPerformed(evt);
            }
        });

        btnIzvestaj.setBackground(new java.awt.Color(0, 115, 173));
        btnIzvestaj.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnIzvestaj.setForeground(new java.awt.Color(255, 255, 255));
        btnIzvestaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlikeDizajn/baseline_show_chart_white_36dp.png"))); // NOI18N
        btnIzvestaj.setText("Izvestaj");
        btnIzvestaj.setBorder(null);
        btnIzvestaj.setFocusPainted(false);
        btnIzvestaj.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnIzvestaj.setIconTextGap(19);
        btnIzvestaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverHandler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeave(evt);
            }
        });
        btnIzvestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzvestajActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(0, 115, 173));
        btnLogOut.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlikeDizajn/logout.png"))); // NOI18N
        btnLogOut.setActionCommand("Odjava");
        btnLogOut.setBorder(null);
        btnLogOut.setFocusPainted(false);
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverHandler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeave(evt);
            }
        });
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnPocetna.setBackground(new java.awt.Color(0, 115, 173));
        btnPocetna.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnPocetna.setForeground(new java.awt.Color(255, 255, 255));
        btnPocetna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlikeDizajn/home-outline.png"))); // NOI18N
        btnPocetna.setText("Pocetna");
        btnPocetna.setBorder(null);
        btnPocetna.setFocusPainted(false);
        btnPocetna.setIconTextGap(17);
        btnPocetna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverHandler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeave(evt);
            }
        });
        btnPocetna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPocetnaActionPerformed(evt);
            }
        });

        btnPodesavanja.setBackground(new java.awt.Color(0, 115, 173));
        btnPodesavanja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SlikeDizajn/PodesavanjaIcon.png"))); // NOI18N
        btnPodesavanja.setBorder(null);
        btnPodesavanja.setFocusPainted(false);
        btnPodesavanja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverHandler(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverLeave(evt);
            }
        });
        btnPodesavanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPodesavanjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfesorViewLeftLayout = new javax.swing.GroupLayout(ProfesorViewLeft);
        ProfesorViewLeft.setLayout(ProfesorViewLeftLayout);
        ProfesorViewLeftLayout.setHorizontalGroup(
            ProfesorViewLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfesorViewLeftLayout.createSequentialGroup()
                .addGroup(ProfesorViewLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfesorViewLeftLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfesorViewLeftLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(imePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfesorViewLeftLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnPocetna, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfesorViewLeftLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnRezultatiTesta, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfesorViewLeftLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnIzvestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProfesorViewLeftLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnSastaviTest, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProfesorViewLeftLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnPodesavanja, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(180, 180, 180))
        );
        ProfesorViewLeftLayout.setVerticalGroup(
            ProfesorViewLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfesorViewLeftLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(imePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnPocetna, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnRezultatiTesta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnIzvestaj, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSastaviTest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ProfesorViewLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPodesavanja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        pnlMainContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainContent.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jButton3.setBackground(new java.awt.Color(246, 83, 20));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DODAJ LEKCIJE");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 187, 0));
        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DODAJ VEZBE");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainContentLayout = new javax.swing.GroupLayout(pnlMainContent);
        pnlMainContent.setLayout(pnlMainContentLayout);
        pnlMainContentLayout.setHorizontalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContentLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pnlMainContentLayout.setVerticalGroup(
            pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainContentLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(ProfesorViewLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfesorViewLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMainContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1171, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilActionPerformed
        Navigacija.PromeniPanel(this.pnlMainContent, new PanelProfesor(trenutniKorisnik));
    }//GEN-LAST:event_btnProfilActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        try {
            MainFrame m = new MainFrame();
            m.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FrameUcenik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnSastaviTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSastaviTestActionPerformed
        PanelSastaviTest newPnl;
        try {
            Navigacija.PromeniPanel(this.pnlMainContent, new PanelSastaviTest(trenutniKorisnik, listaPredmeta));
        } catch (SQLException ex) {
            Logger.getLogger(FrameProfesor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSastaviTestActionPerformed

    private void btnRezultatiTestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRezultatiTestaActionPerformed
        PanelRezultatiTesta newPnl;
        try {
            Navigacija.PromeniPanel(this.pnlMainContent, new PanelRezultatiTesta(trenutniKorisnik));
        } catch (SQLException ex) {
            Logger.getLogger(FrameProfesor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRezultatiTestaActionPerformed

    private void HoverHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverHandler
        hoverButton((JButton) evt.getSource());
    }//GEN-LAST:event_HoverHandler

    private void HoverLeave(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverLeave
        hoverButtonExit((JButton) evt.getSource());
    }//GEN-LAST:event_HoverLeave

    private void btnIzvestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzvestajActionPerformed
        PanelIzvestaj newPnl;

        try {
            Navigacija.PromeniPanel(this.pnlMainContent, new PanelIzvestaj(trenutniKorisnik));
        } catch (SQLException ex) {
            Logger.getLogger(FrameProfesor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIzvestajActionPerformed

    private void btnPodesavanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPodesavanjaActionPerformed
        Navigacija.PromeniPanel(this.pnlMainContent, new PanelPromenaLozinke(trenutniKorisnik));
    }//GEN-LAST:event_btnPodesavanjaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FrameProfesorBiraFajl pbf = new FrameProfesorBiraFajl(this.listaPredmeta, "vezbe");
        pbf.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FrameProfesorBiraFajl pbf = new FrameProfesorBiraFajl(this.listaPredmeta, "lekcija");
        pbf.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnPocetnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPocetnaActionPerformed
        PanelProfesorMainChoice newPnl;

        try {
            Navigacija.PromeniPanel(this.pnlMainContent, new PanelProfesorMainChoice(trenutniKorisnik));
        } catch (SQLException ex) {
            Logger.getLogger(FrameProfesor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPocetnaActionPerformed

    private void btnSastaviTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSastaviTestMouseClicked
        this.btnSastaviTest.setBackground(Color.decode("#00A1F1"));
        this.btnRezultatiTesta.setBackground(Color.decode("#0073AD"));

        this.btnProfil.setBackground(Color.decode("#0073AD"));

    }//GEN-LAST:event_btnSastaviTestMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProfesorViewLeft;
    private javax.swing.JButton btnIzvestaj;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPocetna;
    private javax.swing.JButton btnPodesavanja;
    private javax.swing.JButton btnProfil;
    private javax.swing.JButton btnRezultatiTesta;
    private javax.swing.JButton btnSastaviTest;
    private javax.swing.JLabel imePrezime;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlMainContent;
    // End of variables declaration//GEN-END:variables
}
