/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika.ProfesorPaneli;

import SuperMatematika.ZajednickeKlase.DBController;
import SuperMatematika.Model.TestWrapper;
import SuperMatematika.Model.Profesor;
import SuperMatematika.Model.Zadatak;
import SuperMatematika.Model.Predmet;
import java.awt.FlowLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1
 */
public class PanelSastaviTest extends javax.swing.JPanel {

    Profesor trenutniKorisnik;
    ArrayList<Predmet> listaPredmeta;
    ArrayList<JRadioButton> RBlistaRazreda = new ArrayList();
    ArrayList<JRadioButton> RBlistaPredmeta = new ArrayList();
    ArrayList<JRadioButton> RBlistaTromesecja = new ArrayList();
    ArrayList<JCheckBox> CBlistaZadataka = new ArrayList();
    ArrayList<JLabel> zadaciLabele = new ArrayList();
    ArrayList<JButton> brisiButtoni = new ArrayList();
    TestWrapper newTest = new TestWrapper();
    private int iterator = 0;

    public PanelSastaviTest(Profesor tk, ArrayList<Predmet> listaPr) throws SQLException {
        trenutniKorisnik = tk;
        listaPredmeta = listaPr;
        initComponents();

        zadaciLabele.add(zad1);
        zadaciLabele.add(zad2);
        zadaciLabele.add(zad3);
        zadaciLabele.add(zad4);
        zadaciLabele.add(zad5);
        brisiButtoni.add(rmButton1);
        brisiButtoni.add(rmButton2);
        brisiButtoni.add(rmButton3);
        brisiButtoni.add(rmButton4);
        brisiButtoni.add(rmButton5);
        brisiButtoni.forEach(e -> {
            int redniBroj = brisiButtoni.indexOf(e);
            e.setVisible(false);
            e.addActionListener(event -> {
                for (int i = redniBroj; i < iterator; i++) {
                    if (i != iterator - 1) {
                        zadaciLabele.get(i).setText(zadaciLabele.get(i + 1).getText());
                    } else {
                        zadaciLabele.get(i).setText("");
                        brisiButtoni.get(iterator - 1).setVisible(false);
                    }
                }
                iterator--;
            });
        });

        RBlistaRazreda.add(this.jRadioButton1);
        RBlistaRazreda.add(this.jRadioButton3);
        RBlistaRazreda.add(this.jRadioButton2);
        RBlistaRazreda.add(this.jRadioButton4);

        RBlistaTromesecja.add(this.jRadioButton9);
        RBlistaTromesecja.add(this.jRadioButton10);
        RBlistaTromesecja.add(this.jRadioButton11);
        RBlistaTromesecja.add(this.jRadioButton12);

        CBlistaZadataka.add(this.btnSkupovi);
        CBlistaZadataka.add(this.btnDeljivost);
        CBlistaZadataka.add(this.btnGeoObjekti1);
        CBlistaZadataka.add(this.btnOsnaSimetrija);
        CBlistaZadataka.add(this.btnRazlomci);
        CBlistaZadataka.add(this.btnUgao);
        listaPredmeta.forEach(e -> {
            RBlistaPredmeta.add(new JRadioButton(e.getNazivPredmeta()));
        });
        this.pnlPredmeti.removeAll();
        this.pnlPredmeti.revalidate();
        this.pnlPredmeti.setLayout(new FlowLayout());
        RBlistaPredmeta.forEach(e -> {
            System.out.println(e.getText());
            this.btnPredmetiGroup.add(e);
            this.pnlPredmeti.add(e);
        });
        prikaziTestove();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPredmetiGroup = new javax.swing.ButtonGroup();
        btnRazrediGroup = new javax.swing.ButtonGroup();
        btnOdeljenjeGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnBrojTestaGroup = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlRZ = new javax.swing.JPanel();
        lblRazred = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnlPR = new javax.swing.JPanel();
        lblPredmet = new javax.swing.JLabel();
        pnlOD = new javax.swing.JPanel();
        lblOdeljenje = new javax.swing.JLabel();
        btnPR2 = new javax.swing.JButton();
        btnPR1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        pnlPredmeti = new javax.swing.JPanel();
        btnMatematika = new javax.swing.JRadioButton();
        btnFizika = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        pnlRazred = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        pnlOdeljenje = new javax.swing.JPanel();
        txtBrojTesta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        TabPanel = new javax.swing.JTabbedPane();
        pnlOBLASTI = new javax.swing.JPanel();
        pnlOblasti = new javax.swing.JPanel();
        btnSkupovi = new javax.swing.JCheckBox();
        btnOsnaSimetrija = new javax.swing.JCheckBox();
        btnGeoObjekti1 = new javax.swing.JCheckBox();
        btnDeljivost = new javax.swing.JCheckBox();
        btnUgao = new javax.swing.JCheckBox();
        btnRazlomci = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnPrikaziZadatke = new javax.swing.JButton();
        pnlZADACI = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        zadaciTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        pnlIzabraniZadaci = new javax.swing.JPanel();
        zad1 = new javax.swing.JLabel();
        zad3 = new javax.swing.JLabel();
        zad4 = new javax.swing.JLabel();
        zad2 = new javax.swing.JLabel();
        zad5 = new javax.swing.JLabel();
        rmButton1 = new javax.swing.JButton();
        rmButton2 = new javax.swing.JButton();
        rmButton3 = new javax.swing.JButton();
        rmButton4 = new javax.swing.JButton();
        rmButton5 = new javax.swing.JButton();
        submitTest = new javax.swing.JButton();
        pnlTestovi = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaTestova = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setPreferredSize(new java.awt.Dimension(890, 650));

        pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRZ.setBackground(new java.awt.Color(0, 161, 241));
        pnlRZ.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRazred.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRazred.setForeground(new java.awt.Color(255, 255, 255));
        lblRazred.setText("RAZRED");
        pnlRZ.add(lblRazred, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, 20));
        pnlRZ.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -90, 50, 80));

        pnlLeft.add(pnlRZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 131, 200, 40));

        pnlPR.setBackground(new java.awt.Color(246, 83, 20));
        pnlPR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPredmet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPredmet.setForeground(new java.awt.Color(255, 255, 255));
        lblPredmet.setText("PREDMET");
        pnlPR.add(lblPredmet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, 20));

        pnlLeft.add(pnlPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 200, 40));

        pnlOD.setBackground(new java.awt.Color(255, 187, 0));
        pnlOD.setPreferredSize(new java.awt.Dimension(220, 40));
        pnlOD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOdeljenje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblOdeljenje.setForeground(new java.awt.Color(255, 255, 255));
        lblOdeljenje.setText("BROJ TESTA");
        pnlOD.add(lblOdeljenje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, 20));

        pnlLeft.add(pnlOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 261, 200, -1));

        btnPR2.setBackground(new java.awt.Color(124, 187, 0));
        btnPR2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPR2.setForeground(new java.awt.Color(255, 255, 255));
        btnPR2.setText("SACUVAJ");
        btnPR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPR2ActionPerformed(evt);
            }
        });
        pnlLeft.add(btnPR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 551, 200, 40));

        btnPR1.setBackground(new java.awt.Color(204, 204, 204));
        btnPR1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPR1.setForeground(new java.awt.Color(255, 255, 255));
        btnPR1.setText("IZMENI");
        pnlLeft.add(btnPR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 591, 200, 40));
        pnlLeft.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 401, 200, 10));

        pnlPredmeti.setBackground(new java.awt.Color(255, 255, 255));
        pnlPredmeti.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        pnlPredmeti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMatematika.setBackground(new java.awt.Color(255, 255, 255));
        btnPredmetiGroup.add(btnMatematika);
        btnMatematika.setText("Matematika");
        pnlPredmeti.add(btnMatematika, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        btnFizika.setBackground(new java.awt.Color(255, 255, 255));
        btnPredmetiGroup.add(btnFizika);
        btnFizika.setText("Fizika");
        pnlPredmeti.add(btnFizika, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));
        pnlPredmeti.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        pnlLeft.add(pnlPredmeti, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 41, 200, 90));

        pnlRazred.setBackground(new java.awt.Color(255, 255, 255));
        pnlRazred.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        pnlRazred.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        btnRazrediGroup.add(jRadioButton1);
        jRadioButton1.setText("5");
        pnlRazred.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        btnRazrediGroup.add(jRadioButton3);
        jRadioButton3.setText("6");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        pnlRazred.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        btnRazrediGroup.add(jRadioButton2);
        jRadioButton2.setText("7");
        pnlRazred.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        btnRazrediGroup.add(jRadioButton4);
        jRadioButton4.setText("8");
        pnlRazred.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        pnlLeft.add(pnlRazred, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 171, 200, 90));

        pnlOdeljenje.setBackground(new java.awt.Color(255, 255, 255));
        pnlOdeljenje.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        pnlOdeljenje.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlOdeljenje.add(txtBrojTesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 20));

        pnlLeft.add(pnlOdeljenje, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 301, 200, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jRadioButton9.setBackground(new java.awt.Color(255, 255, 255));
        btnBrojTestaGroup.add(jRadioButton9);
        jRadioButton9.setText("1");

        jRadioButton10.setBackground(new java.awt.Color(255, 255, 255));
        btnBrojTestaGroup.add(jRadioButton10);
        jRadioButton10.setText("2");

        jRadioButton11.setBackground(new java.awt.Color(255, 255, 255));
        btnBrojTestaGroup.add(jRadioButton11);
        jRadioButton11.setText("4");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jRadioButton12.setBackground(new java.awt.Color(255, 255, 255));
        btnBrojTestaGroup.add(jRadioButton12);
        jRadioButton12.setText("3");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton9))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButton10, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jRadioButton11, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(0, 40, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jRadioButton9)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton12)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jRadioButton10)
                    .addGap(17, 17, 17)
                    .addComponent(jRadioButton11)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlLeft.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 451, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 255, 0));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("TROMESECJE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlLeft.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 401, -1, -1));

        TabPanel.setBackground(new java.awt.Color(246, 83, 20));
        TabPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        TabPanel.setForeground(new java.awt.Color(255, 255, 255));
        TabPanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pnlOBLASTI.setBackground(new java.awt.Color(255, 255, 255));

        pnlOblasti.setBackground(new java.awt.Color(255, 255, 255));
        pnlOblasti.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        btnSkupovi.setBackground(new java.awt.Color(255, 255, 255));
        btnSkupovi.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSkupovi.setForeground(new java.awt.Color(153, 153, 153));
        btnSkupovi.setText("Skupovi");
        btnSkupovi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSkupoviSkupoviCheck(evt);
            }
        });
        btnSkupovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkupoviActionPerformed(evt);
            }
        });

        btnOsnaSimetrija.setBackground(new java.awt.Color(255, 255, 255));
        btnOsnaSimetrija.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnOsnaSimetrija.setForeground(new java.awt.Color(153, 153, 153));
        btnOsnaSimetrija.setText("Osna simetrija");
        btnOsnaSimetrija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsnaSimetrijaActionPerformed(evt);
            }
        });

        btnGeoObjekti1.setBackground(new java.awt.Color(255, 255, 255));
        btnGeoObjekti1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnGeoObjekti1.setForeground(new java.awt.Color(153, 153, 153));
        btnGeoObjekti1.setText("Geometrijski objekti");
        btnGeoObjekti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeoObjekti1ActionPerformed(evt);
            }
        });

        btnDeljivost.setBackground(new java.awt.Color(255, 255, 255));
        btnDeljivost.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnDeljivost.setForeground(new java.awt.Color(153, 153, 153));
        btnDeljivost.setText("Deljivost");
        btnDeljivost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeljivostActionPerformed(evt);
            }
        });

        btnUgao.setBackground(new java.awt.Color(255, 255, 255));
        btnUgao.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnUgao.setForeground(new java.awt.Color(153, 153, 153));
        btnUgao.setText("Ugao");
        btnUgao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUgaoActionPerformed(evt);
            }
        });

        btnRazlomci.setBackground(new java.awt.Color(255, 255, 255));
        btnRazlomci.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnRazlomci.setForeground(new java.awt.Color(153, 153, 153));
        btnRazlomci.setText("Razlomci");
        btnRazlomci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRazlomciActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Prosti i slozeni brojevi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Operacije sa skupovima");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Skup prirodnih brojeva");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Pojam skupa");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Osnovni geometrijski pojmovi");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Delovi prave i ravni");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Kruznice i krugovi");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Simetrala duzi i ugla");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Deljivost nekim brojevima");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Pojam deljivosti");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Pojam ugla");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Uporedjivanje uglova");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Vrste uglova");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Pojam razlomka");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Vrste razlomka");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Mnozenje i deljenje");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Pojam osne sitmetrije");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Osna simetricnost");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout pnlOblastiLayout = new javax.swing.GroupLayout(pnlOblasti);
        pnlOblasti.setLayout(pnlOblastiLayout);
        pnlOblastiLayout.setHorizontalGroup(
            pnlOblastiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
            .addComponent(jSeparator4)
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(btnGeoObjekti1))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel12))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(171, 171, 171)
                .addComponent(jLabel13))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnRazlomci)
                .addGap(185, 185, 185)
                .addComponent(btnOsnaSimetrija))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel15))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel5))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel6))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(btnUgao))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnSkupovi))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel9))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel18))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel11))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel8))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel7))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel14))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel17))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnDeljivost))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel16))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(610, 610, 610)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlOblastiLayout.setVerticalGroup(
            pnlOblastiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnGeoObjekti1)
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addGap(73, 73, 73)
                .addComponent(jLabel10)
                .addGap(13, 13, 13)
                .addComponent(jLabel12)
                .addGap(13, 13, 13)
                .addGroup(pnlOblastiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addGap(43, 43, 43)
                .addGroup(pnlOblastiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlOblastiLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlOblastiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRazlomci)
                            .addComponent(btnOsnaSimetrija))))
                .addGap(39, 39, 39)
                .addComponent(jLabel15))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel5))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel6))
            .addComponent(jSeparator1)
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnUgao))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnSkupovi))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel9))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabel18))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel11))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(jLabel8))
            .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel7))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jLabel17))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnDeljivost))
            .addGroup(pnlOblastiLayout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(jLabel16))
        );

        btnPrikaziZadatke.setBackground(new java.awt.Color(124, 187, 0));
        btnPrikaziZadatke.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrikaziZadatke.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikaziZadatke.setText("Nastavi");
        btnPrikaziZadatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziZadatkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOBLASTILayout = new javax.swing.GroupLayout(pnlOBLASTI);
        pnlOBLASTI.setLayout(pnlOBLASTILayout);
        pnlOBLASTILayout.setHorizontalGroup(
            pnlOBLASTILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOblasti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPrikaziZadatke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlOBLASTILayout.setVerticalGroup(
            pnlOBLASTILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOBLASTILayout.createSequentialGroup()
                .addComponent(pnlOblasti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(btnPrikaziZadatke, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnPrikaziZadatke.getAccessibleContext().setAccessibleName("NASTAVI");

        TabPanel.addTab("OBLASTI", pnlOBLASTI);

        pnlZADACI.setBackground(new java.awt.Color(255, 255, 255));

        zadaciTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        zadaciTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zadaciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "id_zadatka", "oblast", "slika"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        zadaciTable.setGridColor(new java.awt.Color(204, 204, 204));
        zadaciTable.setRowHeight(30);
        zadaciTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zadaciTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(zadaciTable);
        if (zadaciTable.getColumnModel().getColumnCount() > 0) {
            zadaciTable.getColumnModel().getColumn(0).setResizable(false);
            zadaciTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Izabrani zadaci");

        pnlIzabraniZadaci.setBackground(new java.awt.Color(255, 255, 255));
        pnlIzabraniZadaci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        zad1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zad1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        zad3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zad3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        zad4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zad4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        zad2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zad2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        zad5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zad5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        rmButton1.setBackground(new java.awt.Color(246, 83, 20));
        rmButton1.setForeground(new java.awt.Color(255, 255, 255));
        rmButton1.setText("X");
        rmButton1.setFocusPainted(false);

        rmButton2.setBackground(new java.awt.Color(246, 83, 20));
        rmButton2.setForeground(new java.awt.Color(255, 255, 255));
        rmButton2.setText("X");
        rmButton2.setFocusPainted(false);

        rmButton3.setBackground(new java.awt.Color(246, 83, 20));
        rmButton3.setForeground(new java.awt.Color(255, 255, 255));
        rmButton3.setText("X");
        rmButton3.setFocusPainted(false);

        rmButton4.setBackground(new java.awt.Color(246, 83, 20));
        rmButton4.setForeground(new java.awt.Color(255, 255, 255));
        rmButton4.setText("X");
        rmButton4.setFocusPainted(false);

        rmButton5.setBackground(new java.awt.Color(246, 83, 20));
        rmButton5.setForeground(new java.awt.Color(255, 255, 255));
        rmButton5.setText("X");
        rmButton5.setFocusPainted(false);

        javax.swing.GroupLayout pnlIzabraniZadaciLayout = new javax.swing.GroupLayout(pnlIzabraniZadaci);
        pnlIzabraniZadaci.setLayout(pnlIzabraniZadaciLayout);
        pnlIzabraniZadaciLayout.setHorizontalGroup(
            pnlIzabraniZadaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzabraniZadaciLayout.createSequentialGroup()
                .addGroup(pnlIzabraniZadaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zad2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zad5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zad4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zad3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIzabraniZadaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rmButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rmButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIzabraniZadaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rmButton3)
                        .addComponent(rmButton4)
                        .addComponent(rmButton5))))
        );
        pnlIzabraniZadaciLayout.setVerticalGroup(
            pnlIzabraniZadaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzabraniZadaciLayout.createSequentialGroup()
                .addGroup(pnlIzabraniZadaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rmButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIzabraniZadaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rmButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIzabraniZadaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zad3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rmButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIzabraniZadaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zad4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rmButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIzabraniZadaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zad5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rmButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
        );

        submitTest.setBackground(new java.awt.Color(124, 187, 0));
        submitTest.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        submitTest.setForeground(new java.awt.Color(255, 255, 255));
        submitTest.setText("Submit");
        submitTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlIzabraniZadaci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(pnlIzabraniZadaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(submitTest, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlZADACILayout = new javax.swing.GroupLayout(pnlZADACI);
        pnlZADACI.setLayout(pnlZADACILayout);
        pnlZADACILayout.setHorizontalGroup(
            pnlZADACILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZADACILayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );
        pnlZADACILayout.setVerticalGroup(
            pnlZADACILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZADACILayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlZADACILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        TabPanel.addTab("ZADACI", pnlZADACI);

        tabelaTestova.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Predmet", "Razred", "Odeljenje", "Broj testa"
            }
        ));
        tabelaTestova.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaTestova.setRowHeight(30);
        jScrollPane2.setViewportView(tabelaTestova);

        javax.swing.GroupLayout pnlTestoviLayout = new javax.swing.GroupLayout(pnlTestovi);
        pnlTestovi.setLayout(pnlTestoviLayout);
        pnlTestoviLayout.setHorizontalGroup(
            pnlTestoviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        pnlTestoviLayout.setVerticalGroup(
            pnlTestoviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        TabPanel.addTab("TESTOVI", pnlTestovi);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(TabPanel))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(TabPanel)
                        .addGap(2, 2, 2)))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void btnRazlomciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRazlomciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRazlomciActionPerformed

    private void btnUgaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUgaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUgaoActionPerformed

    private void btnDeljivostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeljivostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeljivostActionPerformed

    private void btnGeoObjekti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeoObjekti1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGeoObjekti1ActionPerformed

    private void btnOsnaSimetrijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsnaSimetrijaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnOsnaSimetrijaActionPerformed

    private void btnSkupoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkupoviActionPerformed
        // TODO add your handling code here:
        if (this.btnSkupovi.isSelected() == false) {

        }
    }//GEN-LAST:event_btnSkupoviActionPerformed

    private void btnSkupoviSkupoviCheck(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSkupoviSkupoviCheck
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSkupoviSkupoviCheck

    private void btnPR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPR2ActionPerformed

        if (ImaPraznihPolja()){
            JOptionPane.showMessageDialog(null, "Niste uneli potrebne podatke");
            return;
        }
        
        newTest.setNastavnik(this.trenutniKorisnik.getUsername());
        
        for (int i = 0; i < 4; i++) {
            if (this.RBlistaRazreda.get(i).isSelected()) {
                newTest.setRazred(i + 5);
                break;
            }
        }
        
        for (int i = 0; i < this.listaPredmeta.size(); i++) {
            if (this.RBlistaPredmeta.get(i).isSelected()) {
                try {
                    newTest.setId_predmeta(DBController.require().getIdPredmeta(this.RBlistaPredmeta.get(i).getText(), newTest.getRazred()));
                } catch (SQLException ex) {
                    Logger.getLogger(PanelSastaviTest.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            }
        }
        
        newTest.setRedni_broj_testa(Integer.parseInt(txtBrojTesta.getText()));

        for (int i = 0; i < 4; i++) {
            if (this.RBlistaTromesecja.get(i).isSelected()) {
                System.out.println(Integer.parseInt(RBlistaTromesecja.get(i).getText()));
                newTest.setTromesecje(Integer.parseInt(RBlistaTromesecja.get(i).getText()));
                break;
            }
        }


    }//GEN-LAST:event_btnPR2ActionPerformed

    private boolean ImaPraznihPolja() {
        return txtBrojTesta.getText().equals(""); // i jos toga treba ali ovo samo za sad
    }
    
    String getSelected(ArrayList<JRadioButton> j) {
        for (int i = 0; i < j.size(); i++) {
            if (j.get(i).isSelected()) {
                return j.get(i).getText();
            }
        }
        return null;
    }

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void btnPrikaziZadatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziZadatkeActionPerformed
        ArrayList<String> izabraneOblasti = new ArrayList();
        DefaultTableModel dm = (DefaultTableModel) this.zadaciTable.getModel();
        dm.setRowCount(0);
        this.CBlistaZadataka.forEach(e -> {
            if (e.isSelected()) {
                izabraneOblasti.add(e.getText());
            }
        });
        try {
            ArrayList<Zadatak> zadaci = DBController.require().prikaziZadatke(getSelected(RBlistaPredmeta), getSelected(this.RBlistaRazreda), izabraneOblasti);
            try {
                zadaci.forEach(z -> {
                    System.out.print(z.getOblast());
                    Object[] row = {z.getId_zadatka(), z.getOblast(), z.getSlika_zadatka()};
                    ((DefaultTableModel) this.zadaciTable.getModel()).insertRow(0, row);
                });

                this.TabPanel.setSelectedIndex(1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nista izabrali nijednu oblast!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelSastaviTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrikaziZadatkeActionPerformed

    private void submitTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitTestActionPerformed
        if (iterator >= 5) {
            if (JOptionPane.showConfirmDialog(null, "Jeste li sigurni?") == 0) {
                ArrayList<Integer> listaIzabranihZadataka = new ArrayList();

                zadaciLabele.forEach(e -> {
                    System.out.println("VREDNOST ZADATKA:" + Integer.valueOf(e.getText()));
                    listaIzabranihZadataka.add(Integer.valueOf(e.getText()));
                });
                try {
                    DBController.require().kreirajTest(trenutniKorisnik, newTest, listaIzabranihZadataka);
                } catch (SQLException ex) {
                    Logger.getLogger(PanelSastaviTest.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            prikaziTestove();
            TabPanel.setSelectedIndex(2);
        } else {
            JOptionPane.showMessageDialog(null, "Niste dali 5 zadataka");
        }
    }//GEN-LAST:event_submitTestActionPerformed

    private void zadaciTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zadaciTableMouseClicked
        if (evt.getClickCount() == 2 && iterator < 5) {
            this.zadaciLabele.get(iterator).setText(zadaciTable.getValueAt(zadaciTable.getSelectedRow(), 0).toString());
            this.brisiButtoni.get(iterator).setVisible(true);
            iterator++;
        }
    }//GEN-LAST:event_zadaciTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.ButtonGroup btnBrojTestaGroup;
    private javax.swing.JCheckBox btnDeljivost;
    private javax.swing.JRadioButton btnFizika;
    private javax.swing.JCheckBox btnGeoObjekti1;
    private javax.swing.JRadioButton btnMatematika;
    private javax.swing.ButtonGroup btnOdeljenjeGroup;
    private javax.swing.JCheckBox btnOsnaSimetrija;
    private javax.swing.JButton btnPR1;
    private javax.swing.JButton btnPR2;
    private javax.swing.ButtonGroup btnPredmetiGroup;
    private javax.swing.JButton btnPrikaziZadatke;
    private javax.swing.JCheckBox btnRazlomci;
    private javax.swing.ButtonGroup btnRazrediGroup;
    private javax.swing.JCheckBox btnSkupovi;
    private javax.swing.JCheckBox btnUgao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblOdeljenje;
    private javax.swing.JLabel lblPredmet;
    private javax.swing.JLabel lblRazred;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlIzabraniZadaci;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlOBLASTI;
    private javax.swing.JPanel pnlOD;
    private javax.swing.JPanel pnlOblasti;
    private javax.swing.JPanel pnlOdeljenje;
    private javax.swing.JPanel pnlPR;
    private javax.swing.JPanel pnlPredmeti;
    private javax.swing.JPanel pnlRZ;
    private javax.swing.JPanel pnlRazred;
    private javax.swing.JPanel pnlTestovi;
    private javax.swing.JPanel pnlZADACI;
    private javax.swing.JButton rmButton1;
    private javax.swing.JButton rmButton2;
    private javax.swing.JButton rmButton3;
    private javax.swing.JButton rmButton4;
    private javax.swing.JButton rmButton5;
    private javax.swing.JButton submitTest;
    private javax.swing.JTable tabelaTestova;
    private javax.swing.JTextField txtBrojTesta;
    private javax.swing.JLabel zad1;
    private javax.swing.JLabel zad2;
    private javax.swing.JLabel zad3;
    private javax.swing.JLabel zad4;
    private javax.swing.JLabel zad5;
    private javax.swing.JTable zadaciTable;
    // End of variables declaration//GEN-END:variables

    private void prikaziTestove() {
        DefaultTableModel dm = (DefaultTableModel) this.tabelaTestova.getModel();
        dm.setRowCount(0);
        try {
            ArrayList<TestWrapper> testovi = DBController.require().prikaziTestove(this.trenutniKorisnik);
            System.out.println(testovi.size());
            testovi.forEach(z -> {
                System.out.println(z.getId_predmeta());
                Object[] row = {z.getId_predmeta(), z.getRazred(), z.getTromesecje(), z.getRedni_broj_testa()};
                ((DefaultTableModel) this.tabelaTestova.getModel()).insertRow(0, row);
            });
        } catch (SQLException ex) {
            Logger.getLogger(PanelSastaviTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
