/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika.AdminPaneli;

import SuperMatematika.ZajednickeKlase.DBController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Melida
 */
public class PanelDodajProfesora extends javax.swing.JPanel {

    public PanelDodajProfesora() {
        initComponents();
    }

    public void DodajProfesora() throws SQLException {
        int i = Integer.parseInt(this.txtRazred.getText());
        if (!txtUsername.getText().equals("") && !txtPass.getText().equals("") && !txtUsertype.getText().equals("") && !txtIme.getText().equals("") && !txtPrezime.getText().equals("") && !txtDatumR.getText().equals("") && !txtPol.getText().equals("")) {
            DBController.require().DodajKorisnika(this.txtUsername.getText(), this.txtPass.getText(), this.txtUsertype.getText(), this.txtIme.getText(), this.txtPrezime.getText(), this.txtDatumR.getText(), this.txtPol.getText());
            DBController.require().DodajProfesora(this.txtUsername.getText(), this.txtFakultet.getText());
            DBController.require().ProfesorPredaje(this.txtPredmet.getText(), this.txtUsername.getText(), i);
        } else {
            JOptionPane.showMessageDialog(null, "Niste popunili sva polja");
        }
    }

    public void najveciId() throws SQLException {
        long rezultat = DBController.require().getIdPredmeta();
        JOptionPane.showMessageDialog(null, rezultat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUsertype = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDatumR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPol = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFakultet = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPredmet = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRazred = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.GridLayout(10, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("username");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setRequestFocusEnabled(false);
        jPanel2.add(jLabel1);

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsername);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("lozinka");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setRequestFocusEnabled(false);
        jPanel2.add(jLabel2);

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(txtPass);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("tip korisnika");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.setRequestFocusEnabled(false);
        jPanel2.add(jLabel3);

        txtUsertype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsertype.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsertype.setText("profesor");
        jPanel2.add(txtUsertype);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ime");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel5.setRequestFocusEnabled(false);
        jPanel2.add(jLabel5);

        txtIme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIme.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(txtIme);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("prezime");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setRequestFocusEnabled(false);
        jPanel2.add(jLabel6);

        txtPrezime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrezime.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(txtPrezime);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("datum rodjenja");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel7.setRequestFocusEnabled(false);
        jPanel2.add(jLabel7);

        txtDatumR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDatumR.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(txtDatumR);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("pol");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setRequestFocusEnabled(false);
        jPanel2.add(jLabel4);

        txtPol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPol.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(txtPol);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("fakultet");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel8);

        txtFakultet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFakultet.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFakultet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFakultetActionPerformed(evt);
            }
        });
        jPanel2.add(txtFakultet);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("predmet");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel9);

        txtPredmet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPredmet.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPredmetActionPerformed(evt);
            }
        });
        jPanel2.add(txtPredmet);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("razred");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel10);

        txtRazred.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRazred.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRazred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazredActionPerformed(evt);
            }
        });
        jPanel2.add(txtRazred);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 390));

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });
        jPanel1.add(btnSacuvaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 80, 30));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            DodajProfesora();
        } catch (SQLException ex) {
            Logger.getLogger(PanelDodajProfesora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void txtFakultetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFakultetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFakultetActionPerformed

    private void txtPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPredmetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPredmetActionPerformed

    private void txtRazredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazredActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            najveciId();
        } catch (SQLException ex) {
            Logger.getLogger(PanelDodajProfesora.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDatumR;
    private javax.swing.JTextField txtFakultet;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPol;
    private javax.swing.JTextField txtPredmet;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtRazred;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsertype;
    // End of variables declaration//GEN-END:variables
}
