/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperMatematika.UcenikPaneli;

import SuperMatematika.Model.Student;
import java.awt.BorderLayout;
import java.sql.SQLException;

/**
 *
 * @author Melida
 */
public class PanelUcenikPodaci extends javax.swing.JPanel {

    Student trenutniKorisnik;

    public PanelUcenikPodaci(Student tk) {
        trenutniKorisnik = tk;
        initComponents();
        popuniLabele();
    }

    /*private void popuniLabele() {
        lUsername.setText(trenutniKorisnik.username);
        lIme.setText(trenutniKorisnik.ime);
        lPrezime.setText(trenutniKorisnik.prezime);
        lDatumRodjenja.setText(trenutniKorisnik.datumRodjenja.toString());
        lPol.setText(trenutniKorisnik.pol);
        
        // Za student se pamti razred dok se za nastavnika pamti njegov fakultet
            lRazredIliFakultet.setText(((Student)trenutniKorisnik).getRazred() + "");
            // Umesto razred treba da pise fakultet
          
     */
    private void popuniLabele() {
        lUsername1.setText(trenutniKorisnik.getUsername());
        lIme1.setText(trenutniKorisnik.getIme());
        lPrezime1.setText(trenutniKorisnik.getPrezime());
        lDatumRodjenja1.setText(trenutniKorisnik.getDatumRodjenja().toString());
        lPol1.setText(trenutniKorisnik.getPol());

        // Za student se pamti razred dok se za nastavnika pamti njegov fakultet
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUcenikPodaci1 = new javax.swing.JPanel();
        lblUsername1 = new javax.swing.JLabel();
        lblIme1 = new javax.swing.JLabel();
        lblDatumRodjenja1 = new javax.swing.JLabel();
        lblPol1 = new javax.swing.JLabel();
        lUsername1 = new javax.swing.JLabel();
        lIme1 = new javax.swing.JLabel();
        lPrezime1 = new javax.swing.JLabel();
        lDatumRodjenja1 = new javax.swing.JLabel();
        lPol1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pnlUcenikPodaci1.setBackground(new java.awt.Color(255, 255, 255));

        lblUsername1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(153, 153, 153));
        lblUsername1.setText("Username");

        lblIme1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblIme1.setForeground(new java.awt.Color(153, 153, 153));
        lblIme1.setText("Ime i prezime");

        lblDatumRodjenja1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDatumRodjenja1.setForeground(new java.awt.Color(153, 153, 153));
        lblDatumRodjenja1.setText("Datum rodjenja");

        lblPol1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPol1.setForeground(new java.awt.Color(153, 153, 153));
        lblPol1.setText("Pol");

        lUsername1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lUsername1.setForeground(new java.awt.Color(153, 153, 153));
        lUsername1.setText("username");

        lIme1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lIme1.setForeground(new java.awt.Color(153, 153, 153));
        lIme1.setText("ime");

        lPrezime1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lPrezime1.setForeground(new java.awt.Color(153, 153, 153));
        lPrezime1.setText("pprezime");

        lDatumRodjenja1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lDatumRodjenja1.setForeground(new java.awt.Color(153, 153, 153));
        lDatumRodjenja1.setText("datum");

        lPol1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lPol1.setForeground(new java.awt.Color(153, 153, 153));
        lPol1.setText("pol");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator7.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlUcenikPodaci1Layout = new javax.swing.GroupLayout(pnlUcenikPodaci1);
        pnlUcenikPodaci1.setLayout(pnlUcenikPodaci1Layout);
        pnlUcenikPodaci1Layout.setHorizontalGroup(
            pnlUcenikPodaci1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator4)
            .addGroup(pnlUcenikPodaci1Layout.createSequentialGroup()
                .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addGap(1, 1, 1))
            .addGroup(pnlUcenikPodaci1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlUcenikPodaci1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUcenikPodaci1Layout.createSequentialGroup()
                        .addComponent(lblIme1)
                        .addGap(70, 70, 70)
                        .addComponent(lIme1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lPrezime1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUcenikPodaci1Layout.createSequentialGroup()
                        .addComponent(lblUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(lUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUcenikPodaci1Layout.createSequentialGroup()
                        .addComponent(lblDatumRodjenja1)
                        .addGap(52, 52, 52)
                        .addComponent(lDatumRodjenja1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUcenikPodaci1Layout.createSequentialGroup()
                        .addComponent(lblPol1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(lPol1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlUcenikPodaci1Layout.setVerticalGroup(
            pnlUcenikPodaci1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUcenikPodaci1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlUcenikPodaci1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIme1)
                    .addComponent(lIme1)
                    .addComponent(lPrezime1))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(pnlUcenikPodaci1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(pnlUcenikPodaci1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatumRodjenja1)
                    .addComponent(lDatumRodjenja1))
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pnlUcenikPodaci1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPol1)
                    .addComponent(lPol1))
                .addGap(11, 11, 11)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUcenikPodaci1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUcenikPodaci1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 368, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lDatumRodjenja1;
    private javax.swing.JLabel lIme1;
    private javax.swing.JLabel lPol1;
    private javax.swing.JLabel lPrezime1;
    private javax.swing.JLabel lUsername1;
    private javax.swing.JLabel lblDatumRodjenja1;
    private javax.swing.JLabel lblIme1;
    private javax.swing.JLabel lblPol1;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JPanel pnlUcenikPodaci1;
    // End of variables declaration//GEN-END:variables
}
